#!/bin/sh
echo screenrc
grep -q '^termcapinfo xterm\* ti@:te@' /etc/screenrc||echo 'termcapinfo xterm\* ti@:te@'|sudo tee -a /etc/screenrc

echo aliases
grep -q dagelf ~/.bash_aliases||echo '# dagelf
alias apt="sudo apt "
alias pacman="sudo pacman "
alias dpa="docker ps -a "
alias xtv="xtightvncviewer -compresslevel 9 -encodings 'tight copyrect coRRE' -quality 3 "
alias rd="rdesktop -D -K -z -r clipboard:CLIPBOARD -g 1280x720 -u WIN_USER -p WIN_PASS "
' >> ~/.bash_aliases

echo git credentials
git config --global user.email "GITHUB_EMAIL"
git config --global user.name "GITHUB_NAME"
git config --global push.default simple

echo Done\!
