#!/bin/sh -e

if [ $# -lt 1 ]
then
cat << HELP

dockerfile  --  dump dockerfile used to create an image

EXAMPLE: 
    - list dockerfile for ubuntu:latest
       dockerfile ubuntu

    - list dockerfile for php:apache:
       dockerfile php apache

HELP
exit 1
fi

image=$1
tag=$2

echo $image|grep -q \\/||image=library/$image # use library/ unless something else specified

if [ -n $tag ]; then
  tag=`echo $1|cut -d: -f2`
  if [ -n $tag ]; then
    tag=latest;
  fi
fi

#fixme for non library/
curl -s https://hub.docker.com/r/$image/|grep $tag|head -1|cut -d\" -f2|sed s@github.com@raw.githubusercontent.com@|sed s@/blob@@|xargs curl -s

echo #See also: https://hub.docker.com/r/$image/
