#!/bin/sh
# todo: play nice with networkmanager and other firewalls; improve firewall
[ -z "$1" ] && echo -e "Configures & runs dhcp & net sharing on an interface\n  Usage: $0 interface" && exit
echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward
sudo iptables -t nat -A POSTROUTING -j MASQUERADE
sudo iptables -I INPUT -s 192.168.9.0/24 -j ACCEPT
sudo iptables -I FORWARD -s 192.168.9.0/24 -j ACCEPT
sudo ifconfig $1 192.168.9.1 up; sudo dnsmasq -F 192.168.9.10,192.168.9.239 -i $1 -d #--dhcp-option=3 # don't send a default route

