#!/bin/sh
[ 0$1 -gt 0 ] && m=$1 || m=60
echo "Resting for $m minutes..."
sleep 3
echo 0 > /sys/class/rtc/rtc0/wakealarm
echo `date '+%s' -d "+ $m minutes"` > /sys/class/rtc/rtc0/wakealarm
echo mem > /sys/power/state
echo "I'm back!"

