#!/bin/sh
[ -z "$1" ] && { echo "Usage: waitall string # waits untill all existing instances of process with string in commandline exits (excludes new ones that started since)"; exit; }
for a in `ps auxf|grep $1|grep -v $0|awk '{print $2}'`; do while ls -d /proc/$a >/dev/null 2>/dev/null; do sleep 1; done; done
